"""Added users and files_requests

Revision ID: 403dfdaa9d66
Revises: 
Create Date: 2023-03-23 13:53:22.915699

"""
from alembic import op
import sqlalchemy as sa
from src.core.settings import Settings
from src.services.users import UserService
from datetime import date


# revision identifiers, used by Alembic.
revision = '403dfdaa9d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    settings = Settings()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload', sa.Boolean(), nullable=True),
    sa.Column('download', sa.Boolean(), nullable=True),
    sa.Column('get_columns', sa.Boolean(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    users_table = op.create_table('users',
                                  sa.Column('id', sa.Integer(), nullable=False),
                                  sa.Column('username', sa.String(), nullable=True),
                                  sa.Column('password_hashed', sa.String(), nullable=True),
                                  sa.Column('role', sa.String(), nullable=True),
                                  sa.Column('created_at', sa.Date(), nullable=True),
                                  sa.Column('created_by', sa.Integer(), nullable=True),
                                  sa.Column('modified_at', sa.Date(), nullable=True),
                                  sa.Column('modified_by', sa.Integer(), nullable=True),
                                  sa.PrimaryKeyConstraint('id'),
                                  sa.UniqueConstraint('username')
                                  )

    op.bulk_insert(
        users_table,
        [
            {
                'username': settings.admin_username,
                'password_hashed': UserService.hash_password(settings.admin_password),
                'role': 'admin',
                'created_at': date.today(),
                'created_by': -1,
                'modified_at': date.today(),
                'modified_by': -1,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('files_requests')
    # ### end Alembic commands ###
